version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped

  hardhat-node:
    build:
      context: .
      dockerfile: zarf/docker/hardhat/Dockerfile
    container_name: hardhat-node
    ports:
      - "8545:8545"
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: zarf/docker/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - DB_URI=mongodb://mongodb:27017
      - HARDHAT_NODE_URL=http://hardhat-node:8545
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - hardhat-node
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./app/frontend/blogchain-vue
      dockerfile: Dockerfile
    container_name: blogchain-vue
    ports:
      - "8080:80"  
    environment:
      - VUE_APP_BACKEND_URL=http://backend:3000
    restart: unless-stopped
